# version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    restart: unless-stopped
    container_name: node-app
    ports:
      - "${SERVER_PORT:-5050}:${SERVER_PORT:-5050}"
    networks:
      - net1
    depends_on:
      - mongodb
      - redis
    env_file:
    - .env

  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    restart: unless-stopped
    container_name: mongodb
    networks:
      - net1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ljosc
    volumes:
      - mongodb_data:/data/db

  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    restart: unless-stopped
    container_name: redis
    networks:
      - net1
    volumes:
      - redis_data:/data/db

networks:
  net1:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:



services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - DB_URI=mongodb://mongo:27017/dev_discuss

  mongo:
    image: mongo
    ports:
      - "27017:27017"
